# Generated by Django 5.1.4 on 2025-01-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_subcategory_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='pareant_category',
        ),
    ]
