# Generated by Django 5.1.4 on 2025-01-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_subcategory_category_pareant_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='pareant_category',
            new_name='parent_category',
        ),
    ]
